name: rt_chat
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # UI and Icons
  cupertino_icons: ^1.0.8 # iOS-style icons
  flutter_svg: ^2.1.0     # SVG image support
  flutter_screenutil: ^5.9.3 # Responsive UI
  cached_network_image: ^3.4.1 # Image caching
  skeletonizer: ^1.4.3 # Skeleton loading placeholder

  # Routing & Navigation
  go_router: ^15.1.3 # Declarative routing system

  # Firebase (Auth & Database)
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # HTTP & Networking
  http: ^1.4.0
  dio: ^5.8.0+1 # Advanced HTTP client

  # Location Services
  geolocator: ^14.0.1 # Get GPS coordinates
  geocoding: ^4.0.0   # Convert GPS to address

  # Utilities
  url_launcher: ^6.3.1 # Open links, dialers, email etc.
  logger: ^2.5.0 # Logging/debugging
  just_audio: ^0.10.4 # Audio playback
  intl: ^0.20.2 # Date/Time formatting
  pin_code_fields: ^8.0.1 # OTP UI
  shared_preferences: ^2.5.3 # Local key-value storage
  fluttertoast: ^8.2.12 # Toast messages
  window_size: ^0.1.0 # Desktop window control

  # Code Generation Support
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  image_picker: ^1.1.2
  firebase_storage: ^12.4.7
  path: ^1.9.1
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generators
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5

  # Linting & Code Quality
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/button.mp3

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900
